'use strict';
// 완성된 원본 이미지는 큰 화면에 사용하고, 같은 내용을 모바일과 스크린 리더에 제공합니다.
// 자료가 없는 지도 페이지는 의도적으로 비워 둡니다.
const pages = [
  {title:'THE CODE', image:0, cover:true, html:`<div class="logo-signal"><img class="cover-logo" src="assets/the-code-logo.png" alt="더코드 THE CODE" width="5120" height="5120"></div>`},
  {title:'게임 안내', image:1, html:`<div class="center"><p><b>어이, 죄수들—</b><br>아직도 상황 파악이 안 되나 보지?</p><p>여긴 법도 없고, 구해줄 사람도 없는 섬이다.</p><p>하지만 말이지...<br>완전히 쓸모없진 않다는 걸 증명할 기회 정도는 주지.</p><p>지금부터 너희는<br>이 무인도에서 단 <b class="red">한 명</b>만 <b class="red">탈출</b>할 수 있는 <b class="red">게임</b>에 참가한다.</p></div>`},
  {title:'살아남아라', image:2, html:`<div class="center"><p>살고 싶다면—<br><i>찾아라.</i><br><u>의심해라.</u><br>속여라.<br>그리고... <span class="survive red">살아남아라.</span></p><p>네 옆에 있는 놈이<br>네 동료일지, 네 목을 조를 놈일지는—</p><p><b>끝까지 가보기 전엔 아무도 모른다.</b></p><p>시간은 없다.<br>기회는 단 <b>한 번</b>이다.</p></div>`},
  {title:'기본 규칙', image:3, html:`<div class="center"><h1>플레이 시간 : 50분</h1><p><b class="white">플레이 인원</b><br>일반 참가자 + <u>스파이 1명</u></p><p><b class="red">사망 시 탈락하지 않는다.</b><br>아이템, 정보 공유 자유<br>모든 행동은 <b>플레이어의 선택</b>에 따른다.</p><p>누구를 믿을지는 네 <b class="red">선택</b>이다.</p></div>`},
  {title:'탈출 방법', image:4, html:`<h1>탈출 방법</h1><p><b>모든 코드</b> 해독 후, <b class="red">탈출 벙커</b>에 <b>코드 입력.</b></p><p><i>각자의 <b>고유 코드</b>는 총 3줄이며, <b>랜덤</b>이다.</i><span class="sub">상자 파밍, 몬스터 처치 시 <b>코드 조각</b> 획득 가능.<br>모든 플레이어의 코드 해독 방식은 동일하다.</span></p><p><b>관리자</b>에게 <b>코드 조각 3개</b>를 주면, <b>코드 1줄</b>을 받을 수 있다.<br>└ (연구소 1층)</p><p><b>[ 녹음기 ]</b> 사용 시 코드 해독 힌트 획득<span class="sub">하나의 코드에는 여러 개의 힌트가 존재한다.<br>지급 된 <b>[ USB ]</b>로 얻은 힌트를 다시 볼 수 있다.</span></p>`},
  {title:'지도', image:0, map:true, html:`<h1>지도</h1><div class="map-layout"><button type="button" class="map-view" aria-label="지하수로 지도 보기" aria-pressed="false" aria-describedby="map-help"><span class="map-layer surface-layer"><img src="assets/map-surface.png" width="1448" height="1086" alt="지상 지도. 상단 통신타워, 좌측 버려진 오두막, 가운데 폐쇄된 연구소, 우측 아래 폐허 마을. 빨간점은 지하수로."><span class="map-label" style="left:60%;top:9%">통신타워</span><span class="map-label" style="left:2%;top:48%">버려진 오두막</span><span class="map-label" style="left:57%;top:43%">폐쇄된 연구소</span><span class="map-label" style="left:65%;top:89%">폐허 마을</span></span><span class="map-layer underground-layer" aria-hidden="true"><img src="assets/map-underground.png" width="1448" height="1086" alt="지하수로 지도. 상단 빨간점 통신타워, 중앙 빨간점 폐쇄된 연구소, 좌측 빨간점 버려진 오두막, 우측 빨간점 폐허 마을."><span class="map-label" style="left:51%;top:16%">통신타워</span><span class="map-label" style="left:49%;top:43%">폐쇄된 연구소</span><span class="map-label" style="left:5%;top:66%">버려진 오두막</span><span class="map-label" style="left:68%;top:81%">폐허 마을</span></span></button><aside class="map-key"><p id="map-mode" class="map-mode" aria-live="polite">지상</p><p class="map-legend"><span class="map-red" aria-hidden="true"></span> 지하수로</p><p id="map-help" class="map-help"><span class="pointer-help">지도에 마우스를 올리면<br>지하수로가 나타납니다.</span><span class="touch-help">지도를 터치하면<br>지상·지하수로가 전환됩니다.</span></p></aside></div>`},
  {title:'탈출 벙커', image:0, bunker:true, html:`<h1>탈출 벙커</h1><figure class="bunker-photo"><a href="assets/bunker-crt.png" target="_blank" rel="noopener noreferrer" aria-label="벙커 입구 이미지 크게 보기 (새 탭)"><img src="assets/bunker-crt.png" alt="이끼 낀 돌벽과 덩굴 사이, 구리 블록으로 둘러싸인 철문이 있는 벙커 입구" width="1920" height="1009"></a></figure><p class="bunker-description">맵 어딘가에 숨겨진 벙커의 입구입니다.<br>코드를 입력하여 탈출 할 수 있습니다.</p>`},
  {title:'스파이 · 스킬과 승리 조건', image:7, html:`<h1>스파이</h1><p><i>참가자 중 1명 존재.</i><br><b>스파이 스킬</b><span class="sub"><b>[ 글리치 ]</b> : 3초 실명, 60초간 일반 참가자의 최대 체력 5칸으로 감소<br><b>[ 힌트잠금 ]</b> : 444초 마다 1번, 원하는 힌트 하나를 잠궈 볼 수 없게 만듦</span><i class="sub">└ 일반 참가자들은 상자 파밍으로 힌트 잠금 해제 아이템 획득 가능.</i></p><p><b>승리 조건</b><br>40분까지 아무도 탈출 못 할 경우,<br><b>탈출 프로토콜</b>에 적힌 지침대로 <b class="red">혼자 탈출 시 승리.</b></p><p>- <b>삽</b>과 <b>탈출 프로토콜</b>을 통해, <b class="white">별도의 탈출 루트</b> 진행 가능.</p>`},
  {title:'스파이 · 아이템', image:8, html:`<h1>스파이</h1><p>스파이 전용 상점에서 탈출 프로토콜 책, 삽 구매 가능.</p><p><b>[ 책 ]</b> : 좌표 및 탈출 경로 힌트</p><p><b>[ 삽 ]</b> : 특정 좌표의 흙 아래, 탈출에 필요한 [신호탄] 발굴 시 사용</p><p><b>[ 거짓말 탐지기 ]</b> : 스파이 탐지 가능, 파밍으로 획득 가능<span class="sub">거짓말 탐지기는 <u>갯수가 제한되어 있으므로</u> 신중히 사용해야한다.<br>스파이 탐지 <u>최초 성공</u> 시, <b>[ 녹음기 ]</b> 획득 가능.</span></p>`},
  {title:'스파이 · 아이템 상세', image:9, html:`<h1>스파이</h1><p>스파이 전용 상점에서 탈출 프로토콜 책, 삽 구매 가능.</p><p><b>[ 책 ]</b> : 좌표 및 탈출 경로 힌트</p><p><b>[ 삽 ]</b> : 특정 좌표의 흙 아래 묻힌,<br>탈출에 필요한 [신호탄] 발굴 시 사용</p><p><b>[ 거짓말 탐지기 ]</b> : 스파이 탐지 가능, 파밍으로 획득 가능<span class="sub">- <u>갯수가 제한되어 있으므로</u> 신중히 사용해야한다.<br>- 스파이 탐지 <u>최초 성공</u> 시, <b>[ 녹음기 ]</b> 획득 가능.</span></p>`},
  {title:'기타 룰', image:10, html:`<h1>기타 룰</h1><p><b>[ PVP ]</b> : 사람을 죽이면, 가지고 있던 코인 1개를 떨어뜨린다.</p><p><b>[ 탈출 벙커 ]</b> : 코드 입력은 30초마다 가능하다.</p><p><b>[ 명령어 ]</b> : /쓰레기통<br>/책과 깃펜 사용 가능.</p>`},
  {title:'함께 만든 사람들', image:0, credits:true, html:`<div class="credits-layout"><dl class="credit-list"><dt>기획</dt><dd>쿨즈 포포</dd><dt>제작</dt><dd>쿨즈 포포</dd><dt>리소스 디자인</dt><dd>포포</dd><dt>맵</dt><dd>쵸채</dd><dt>룰지 디자인</dt><dd>배츄</dd><dt>룰지 수정 · 웹사이트 제작</dt><dd>포포</dd><dt>로고</dt><dd>포포</dd><dt>영상 일러스트</dt><dd>무채</dd><dt>더빙</dt><dd>핑맨</dd></dl></div><div class="font-credit">글꼴 · <a href="https://github.com/quiple/galmuri" target="_blank" rel="noopener noreferrer">갈무리11 — quiple</a> · <a href="https://github.com/hurss/fonts" target="_blank" rel="noopener noreferrer">도스이야기 Bold — leedheo</a></div>`},
];
const art=document.getElementById('art');
const content=document.getElementById('content');
const previous=document.getElementById('previous');
const next=document.getElementById('next');
let current=0;
function indexFromHash(){const match=location.hash.match(/^#page-(\d+)$/);return match?Math.max(0,Math.min(pages.length-1,Number(match[1])-1)):0;}
function render(){current=indexFromHash();const p=pages[current];art.src=`assets/page-${p.image}.png`;content.innerHTML=p.html;content.className=`content${p.credits?' credits':p.cover?' cover':p.bunker?' bunker':p.map?' map':''}`;content.scrollTop=0;if(p.map)setupMap();document.getElementById('page-title').textContent=p.title;document.getElementById('counter').textContent=`${String(current+1).padStart(2,'0')} / ${pages.length}`;document.getElementById('page').setAttribute('aria-label',p.title);previous.disabled=current===0;next.disabled=current===pages.length-1;document.title=`${p.title} · THE CODE 룰지`;if(current+1<pages.length){const preload=new Image();preload.src=`assets/page-${pages[current+1].image}.png`;}}
function setupMap(){
  const button=content.querySelector('.map-view');let underground=false;
  const show=value=>{underground=value;button.classList.toggle('show-underground',value);button.setAttribute('aria-pressed',String(value));button.setAttribute('aria-label',value?'지상 지도 보기':'지하수로 지도 보기');button.querySelector('.surface-layer').setAttribute('aria-hidden',String(value));button.querySelector('.underground-layer').setAttribute('aria-hidden',String(!value));document.getElementById('map-mode').textContent=value?'지하수로':'지상';};
  button.addEventListener('pointerenter',event=>{if(event.pointerType==='mouse')show(true);});
  button.addEventListener('pointerleave',event=>{if(event.pointerType==='mouse')show(false);});
  button.addEventListener('click',()=>show(!underground));
}
function go(delta){const target=current+delta;if(target<0||target>=pages.length)return;location.hash=`page-${target+1}`;window.scrollTo({top:0,behavior:'instant'});}
previous.addEventListener('click',()=>go(-1));next.addEventListener('click',()=>go(1));
document.addEventListener('keydown',event=>{if(event.altKey||event.ctrlKey||event.metaKey||event.shiftKey||event.target.closest('input,textarea,select,[contenteditable="true"]'))return;if(event.key==='ArrowRight'){event.preventDefault();go(1);}else if(event.key==='ArrowLeft'){event.preventDefault();go(-1);}});
window.addEventListener('hashchange',render);render();
